name:                uuid-list
version:             0.1.0.0
github:              "Cpp-GLeb/uuid-list"
license:             MIT
license-file:        LICENSE
author:              "Cpp-Gleb"
maintainer:          "G23112006@gmail.com"
extra-source-files:  []

library:
  exposed-modules:
    - UUIDList
  source-dirs: src
  dependencies:
    - base >= 4.7 && < 5
  language: Haskell2010

executables:
  uuid-list-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:         -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - uuid-list
